name: scalable-ecommerce-platform-config-service

on:
  push:
    paths:
      - 'services/${{ github.workflow }}/**'
      - '.github/workflows/${{ github.workflow }}.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'services/${{ github.workflow }}/**'
      - '.github/workflows/${{ github.workflow }}.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/${{ github.workflow }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify