name: scalable-ecommerce-platform-product-service

on:
  push:
    paths:
      - 'services/scalable-ecommerce-platform-product-service**'
      - '.github/workflows/scalable-ecommerce-platform-product-service.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'services/scalable-ecommerce-platform-product-service/**'
      - '.github/workflows/scalable-ecommerce-platform-product-service.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/scalable-ecommerce-platform-product-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify

      - name: Run tests
        run: mvn test