name: Product Service CI/CD

env:
  SERVICE_NAME: scalable-ecommerce-platform-product-service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/${{ env.SERVICE_NAME }}/**'
      - '.github/workflows/${{ env.SERVICE_NAME }}.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/${{ env.SERVICE_NAME }}/**'
      - '.github/workflows/${{ env.SERVICE_NAME }}.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/${{ env.SERVICE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify

      - name: Run tests
        run: mvn test